### ISSUE TITLE
Fuzzer failed

### ISSUE THREAD

**Issue by JustinDrake** [sigp/beacon-fuzz#35]
I tried `docker run -it -v `pwd`/workspace:/eth2fuzz/workspace eth2fuzz_lighthouse continuously -q block` and it failed. See screenshot.

![Screenshot 2020-07-01 at 16 07 01](https://user-images.githubusercontent.com/731743/86260298-ffe61e80-bbb4-11ea-9cc5-ba0739c0b3c5.png)

**Comment by mratsim** [comment]
The fuzzer needs some fuzzing ;)

**Comment by pventuzelo** [comment]
Hey @JustinDrake, 

Sorry for the delay, it should be good now with d84970ba258e84243347e8bc07e1f29af56af170
This bug was happening because docker do not keeping in cache temporary files generated during lighthouse first build.

**Comment by JustinDrake** [comment]
Still failing for me. I did `git pull` and reran the docker command—same error.

**Comment by zedt3ster** [comment]
Hey @JustinDrake - thanks for reporting this! 

Did you also run the `make lighthouse` command again after `git pull`? This seems to have fixed it for me :)
