### ISSUE TITLE
make fuzz-prysm fails

### ISSUE THREAD

**Issue by JustinDrake** [sigp/beacon-fuzz#37]
I did `git pull` and then `make fuzz-prysm`. Please see screenshot :)

![Screenshot 2020-07-13 at 07 33 23](https://user-images.githubusercontent.com/731743/87278001-591a5000-c4db-11ea-90ab-df26682d1706.png)

```
#15 21.62 ERROR: An error occurred during the fetch of repository 'com_grail_bazel_toolchain':
#15 21.62    java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/77a87103145f86f03f90475d19c2c8854398a444.tar.gz] to /root/.cache/bazel/_bazel_root/812fa903a697c4f3e92f7a15bbb634dc/external/com_grail_bazel_toolchain/77a87103145f86f03f90475d19c2c8854398a444.tar.gz: GET returned 500 Internal Server Error
#15 21.65 ERROR: no such package '@com_grail_bazel_toolchain//toolchain': java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/77a87103145f86f03f90475d19c2c8854398a444.tar.gz] to /root/.cache/bazel/_bazel_root/812fa903a697c4f3e92f7a15bbb634dc/external/com_grail_bazel_toolchain/77a87103145f86f03f90475d19c2c8854398a444.tar.gz: GET returned 500 Internal Server Error
#15 21.68 INFO: Elapsed time: 21.202s
```

It looks like Github might be at fault here but maybe we can have some sort of retry logic or some other way to fail more gracefully.

**Comment by JustinDrake** [comment]
Lighthouse also not building

![Screenshot 2020-07-13 at 07 48 47](https://user-images.githubusercontent.com/731743/87278850-60425d80-c4dd-11ea-97e5-2cfe74e44c92.png)

**Comment by pventuzelo** [comment]
I think it should be good now, It was due to github shutdown ;)

**Comment by JustinDrake** [comment]
> It was due to github shutdown ;)

Yep. I guess the next question is: Can we have more resilient infrastructure? Having all the clients rely on Github is not super WW3 proof.

**Comment by zedt3ster** [comment]
> > It was due to github shutdown ;)
> 
> Yep. I guess the next question is: Can we have more resilient infrastructure? Having all the clients rely on Github is not super WW3 proof.

Agreed that's not ideal, specially considering the amount of issues GitHub is having lately. I don't think it's in the scope of this particular project to come up with an alternative to GitHub though, so I'll close this issue :)

**Comment by JustinDrake** [comment]
> I don't think it's in the scope of this particular project to come up with an alternative to GitHub though, so I'll close this issue :)

Agreed :) Would it be part of the scope of the Lighthouse project to have a more robust build infrastructure? Maybe an issue should be opened for that project.

**Comment by zedt3ster** [comment]
In my opinion this is a broader issue that potentially affects all eth2 implementations. Perhaps a conversation on the Eth2 discord is best suited for this.

**Comment by JustinDrake** [comment]
> this is a broader issue that potentially affects all eth2 implementations

Agreed. That makes it an opportunity for Lighthouse to stand out I guess ;)
