### ISSUE TITLE
[FUZZ] Nimbus - Unhandled exception: index

### ISSUE THREAD

**Issue by Buttaa** [sigp/beacon-fuzz#43]
I've identified a fuzzer crash and am contributing to the security of Ethereum 2!

## I've done and provided the following:
- [x] Checked to see if any other `[FUZZ]` issue already refers to that crasher
- [x] Attached the crashing input (either attached to the issue as a .zip or .gz, or as a link to a file sharing service)
- [x] Noted the `beacon-fuzz` version or commit used.
- [x] Provided crash output
- [x] Noted the command or fuzzer used to generate the crash
- [x] Name of the original crash file
- [ ] (Optional but optimal) Checked if the crash can be consistently replicated by re-running the input. 

## Info to Reproduce
* Command run: e.g. docker run -it -v C:\Users\beacon-fuzz\eth2fuzz/workspace:/eth2fuzz/workspace eth2fuzz_nimbus continuously -q nimbus -t 3600
* Crasher file name: crash-21b83413fb627d0fe2d5d5f57b2867cb5f401810
* Client exercised: nimbus
* Fuzzing engine used (if applicable):

## Crash output 

```console
#2081   REDUCE cov: 1056 ft: 1967 corp: 79/45Kb exec/s: 2081 rss: 43Mb L: 130/4096 MS: 1 EraseBytes-
fatal.nim(49)            sysFatal
Error: unhandled exception: index -7378697629483820647 not in 0 .. 255 [IndexError]
==7060== ERROR: libFuzzer: fuzz target exited
    #0 0x461333  (/eth2fuzz/workspace/nimlibfuzzer/nimbus_proposer_slashing+0x461333)
    #1 0x406876  (/eth2fuzz/workspace/nimlibfuzzer/nimbus_proposer_slashing+0x406876)
    #2 0x418267  (/eth2fuzz/workspace/nimlibfuzzer/nimbus_proposer_slashing+0x418267)
    #3 0x7f1a1baf90f0  (/lib/x86_64-linux-gnu/libc.so.6+0x430f0)
    #4 0x7f1a1baf91e9  (/lib/x86_64-linux-gnu/libc.so.6+0x431e9)
    #5 0x56295f  (/eth2fuzz/workspace/nimlibfuzzer/nimbus_proposer_slashing+0x56295f)
    #6 0x5c3167  (/eth2fuzz/workspace/nimlibfuzzer/nimbus_proposer_slashing+0x5c3167)
    #7 0x5c3ed2  (/eth2fuzz/workspace/nimlibfuzzer/nimbus_proposer_slashing+0x5c3ed2)
    #8 0x418917  (/eth2fuzz/workspace/nimlibfuzzer/nimbus_proposer_slashing+0x418917)
    #9 0x423184  (/eth2fuzz/workspace/nimlibfuzzer/nimbus_proposer_slashing+0x423184)
    #10 0x4247ef  (/eth2fuzz/workspace/nimlibfuzzer/nimbus_proposer_slashing+0x4247ef)
    #11 0x413bac  (/eth2fuzz/workspace/nimlibfuzzer/nimbus_proposer_slashing+0x413bac)
    #12 0x406a92  (/eth2fuzz/workspace/nimlibfuzzer/nimbus_proposer_slashing+0x406a92)
    #13 0x7f1a1bad7b96  (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #14 0x406ae9  (/eth2fuzz/workspace/nimlibfuzzer/nimbus_proposer_slashing+0x406ae9)

SUMMARY: libFuzzer: fuzz target exited
MS: 4 ChangeBit-InsertByte-CopyPart-CrossOver-; base unit: a99a351f04ddb516bbe9da98260fdd389af6d360
artifact_prefix='./'; Test unit written to ./crash-21b83413fb627d0fe2d5d5f57b2867cb5f401810
Fuzzer failed so we'll continue with the next one
[eth2fuzz] Testing FuzzerNimLibfuzzer is available
[eth2fuzz] Starting fuzzing of nimbus_voluntary_exit with libfuzzer
testing - ETH2FUZZ_BEACONSTATE
/eth2fuzz/workspace/corpora/beaconstate/59b77505269d4989277b9ff29eca927f.ssz
OK
5572192
INFO: Seed: 1930180755
INFO: Loaded 1 modules   (16250 inline 8-bit counters): 16250 [0x855828, 0x8597a2),
```

## Your Environment

* Fuzzer ran: docker run -it -v C:\Users\beacon-fuzz\eth2fuzz/workspace:/eth2fuzz/workspace eth2fuzz_lodestar continuously -q lodestar -t 3600
* Version/Commit used: cbee3d9
* Operating System and version: windows10

[crash-21b83413fb627d0fe2d5d5f57b2867cb5f401810.zip](https://github.com/sigp/beacon-fuzz/files/4923298/crash-21b83413fb627d0fe2d5d5f57b2867cb5f401810.zip)

**Comment by pventuzelo** [comment]
Thanks for reporting ;) 

After verification, this bug is a duplicated of https://github.com/sigp/beacon-fuzz/issues/40 and has been reported [here](https://github.com/status-im/nim-beacon-chain/issues/1323).
