### ISSUE TITLE
[FUZZ] OOM in lodestar_enr

### ISSUE THREAD

**Issue by Daft-Wullie** [sigp/beacon-fuzz#45]
I've identified a fuzzer crash and am contributing to the security of Ethereum 2!

## I've done and provided the following:
- [x] Checked to see if any other `[FUZZ]` issue already refers to that crasher
- [x] Attached the crashing input (either attached to the issue as a .zip or .gz, or as a link to a file sharing service)
- [x] Noted the `beacon-fuzz` version or commit used.
- [x] Provided crash output
- [x] Noted the command or fuzzer used to generate the crash
- [x] Name of the original crash file
- [ ] (Optional but optimal) Checked if the crash can be consistently replicated by re-running the input. 

## Info to Reproduce
* Command run: e.g. `make fuzz-all`
* Crasher file name: crash-333c4abf56a03bb10a790ecf860a8dd41557849c8c635bf1e66d9f2c8a80f3d6
[crash-333c4abf56a03bb10a790ecf860a8dd41557849c8c635bf1e66d9f2c8a80f3d6.zip](https://github.com/sigp/beacon-fuzz/files/4924616/crash-333c4abf56a03bb10a790ecf860a8dd41557849c8c635bf1e66d9f2c8a80f3d6.zip)
* Client exercised: lodestar
* Fuzzing engine used (if applicable): jsfuzz

## Crash output and stacktrace

```#22402 PULSE     cov: 6738 corp: 3562 exec/s: 172 rss: 159.9 MB
#22477 PULSE     cov: 6738 corp: 3562 exec/s: 24 rss: 159.9 MB
#22477 PULSE     cov: 6738 corp: 3562 exec/s: 0 rss: 412.4 MB
#22477 PULSE     cov: 6738 corp: 3562 exec/s: 0 rss: 663.46 MB
#22477 PULSE     cov: 6738 corp: 3562 exec/s: 0 rss: 965.88 MB
#22477 PULSE     cov: 6738 corp: 3562 exec/s: 0 rss: 1050.84 MB
#22477 PULSE     cov: 6738 corp: 3562 exec/s: 0 rss: 1356.09 MB
#22477 PULSE     cov: 6738 corp: 3562 exec/s: 0 rss: 1562.6 MB
#22477 PULSE     cov: 6738 corp: 3562 exec/s: 0 rss: 1775.48 MB
#22477 PULSE     cov: 6738 corp: 3562 exec/s: 0 rss: 2004.07 MB
#22477 PULSE     cov: 6738 corp: 3562 exec/s: 0 rss: 2005.75 MB
MEMORY OOM: exceeded 2048 MB. Killing worker
Worker killed
crash was written to crash-333c4abf56a03bb10a790ecf860a8dd41557849c8c635bf1e66d9f2c8a80f3d6
Worker exited
```

## Your Environment

* Fuzzer ran: eth2fuzz
* Version/Commit used:
* Operating System and version: Ubuntu 20.04

**Comment by pventuzelo** [comment]
Look like a duplicate of https://github.com/ChainSafe/discv5/issues/64.

Nevertheless I prefer to keep this issue open until it is fixed.
