### ISSUE TITLE
[BUG] Makefile:103: recipe for target 'p2pd' failed

### ISSUE THREAD

**Issue by SeaMonkey82** [sigp/beacon-fuzz#53]
Quickstart steps fail during build process.

## Description

Attempted to use Quickstart guide in Linux Mint 20, but build process fails.

## Expected Behavior

Build process completes and fuzzer runs.

## Actual Behavior

Build process fails.

## Possible Fix

I noticed that a number of packages are downloaded from the Ubuntu 18.04 repo even though I'm using a distribution based on Ubuntu 20.04

## Steps to Reproduce

`git clone --depth 1 --recurse-submodules https://github.com/sigp/beacon-fuzz.git`
`git clone --depth 1 https://github.com/sigp/beacon-fuzz-corpora.git`
`cd beacon-fuzz`
`sudo ./runfuzzer.sh block_header ../beacon-fuzz-corpora/0-9-1/mainnet/block_header/ ../beacon-fuzz-corpora/0-9-1/mainnet/beaconstate`

## Your Environment

* Version/Commit used: c8373eabcb9cc7439f9711f0f795b6cbdb665344
* Operating System and version: Linux Mint 20

**Comment by zedt3ster** [comment]
Thanks @SeaMonkey82. This part of the project is not currently maintained and is actually being completely revamped - see the branch [`beaconfuzz_v2`](https://github.com/sigp/beacon-fuzz/tree/beaconfuzz_v2).

Once that branch is merged, this issue will be resolved.

**Comment by zedt3ster** [comment]
The PRs #55 and #56 have been merged. Feel free to reopen this issue if you're still having problems running any of our fuzzing tools @SeaMonkey82
